//
// Created by Administrator on 2022/10/28 0028.
//

#ifndef DATA_STRUCTURE_LIST_DATA_STRUCTURE_BASE_DEFINE_H
#define DATA_STRUCTURE_LIST_DATA_STRUCTURE_BASE_DEFINE_H

#include "linklist.h"
#include "stack.h"

#endif //DATA_STRUCTURE_LIST_DATA_STRUCTURE_BASE_DEFINE_H
