
name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [core]
jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      # Checkout the core branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # initial
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      # generate all assets 
      - name: Install all denpendiensy
        run: pnpm install
      - name: Pull all
        run: pnpm run sync
      - name: Run build 
        run: pnpm run build
      # Push all the assets
      - name: Push
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: master
          author: couriourc<godakid@outlook.com>
          build_dir: public
          
      
        
        
      
        
